# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master
      - azure-pipelines
      - refs/tags/*

pool: 'Default'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc

- script: |
    echo "Clean up container"
    docker rm -f nivo
    echo "Create new container"
    docker run --name nivo -v $(Build.SourcesDirectory):/app -w /app node:12.18.4 ./build.sh
  displayName: 'Build modules on nivo container'

- script: |
    docker cp nivo:/app/packages/. $(Build.SourcesDirectory)\packages
  displayName: 'Copy modules from nivo container'

- script: |
    cd .\packages\bar
    npm publish
  displayName: 'Publishing bar module'

- script: |
    docker rm -f nivo
  displayName: 'Remove nivo container'