# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master
      - azure-pipelines
      - refs/tags/*

pool: 'Default'

steps:
- script: |
    docker run -v $(Build.SourcesDirectory):/app -w /app node:12.18.4 ./build.sh
  displayName: 'Run docker & build modules'

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc

- script: npm publish